[package]
name = "nami-index-nav"
version = "0.0.0"
authors = []
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[features]
# use library feature to disable all instantiate/execute/query exports
library = []

[dependencies]
nami-rs = { workspace = true }
cosmwasm-schema = { workspace = true }
cosmwasm-std = { workspace = true }
cw-utils = { workspace = true }
cw-storage-plus = { workspace = true }
cw2 = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
rujira-rs = { workspace = true }

[dev-dependencies]
cw-multi-test = { workspace = true }
rujira-rs-testing = { workspace = true }
rujira-fin = { workspace = true }
anyhow = { workspace = true }
nami-rs-testing = { workspace = true }

