[package]
name = "nami-index-nav"
version = "1.0.1"
authors = []
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package.metadata.thorchain]
audits = [
    "https://www.halborn.com/audits/thorchain/nami-protocol-rujira-index-product-0612c8"
]
auditors = [
    "Halborn"
]
docs = "https://docs.rujira.network/products/ruji-index"
commit = "3efb8706f2438323d5dbae29c337a11a6509de30"
deployers = [
    "thor1zjwanvezcjp6hefgt6vqfnrrdm8yj9za3s8ss0"
]

[lib]
crate-type = ["cdylib", "rlib"]

[features]
# use library feature to disable all instantiate/execute/query exports
library = []

[dependencies]
nami-rs = { workspace = true }
cosmwasm-schema = { workspace = true }
cosmwasm-std = { workspace = true }
cw-utils = { workspace = true }
cw-storage-plus = { workspace = true }
cw2 = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
rujira-rs = { workspace = true }

[dev-dependencies]
cw-multi-test = { workspace = true }
rujira-rs-testing = { workspace = true }
rujira-fin = { workspace = true }
anyhow = { workspace = true }
nami-rs-testing = { workspace = true }

